### ISSUE TITLE
Your code is not working plz help me to figureout my mistake

### ISSUE THREAD

**Issue by PARKER-X** [scalablescripts/fastapi-microservices#2]
My code https://github.com/scalablescripts/fastapi-microservices/tree/master/inventory
Post requst gives error

**Comment by vcnwafor** [comment]
@PARKER-X post a sample of the error.

**Comment by PARKER-X** [comment]
> @PARKER-X post a sample of the error.

I think these error produced by redis fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class 'inventory.schema.Product'> is a valid Pydantic field type. If you are using a return type annotation that is not a valid Pydantic field (e.g. Union[Response, dict, None]) you can disable generating the response model from the type annotation with the path operation decorator parameter response_model=None. Read more: https://fastapi.tiangolo.com/tutorial/response-model/

**Comment by vcnwafor** [comment]
below is the changes I made to get it working.
`from pydantic import BaseModel

class ProductCreate(BaseModel):
    name: str
    price: float
    quantity: int


@app.post('/products')
def create(product: ProductCreate):
    print("product found", product)
    new_product = Product(**product.dict())
    new_product.save()
    return new_product
`

**Comment by PARKER-X** [comment]
@vcnwafor It's not working yet

**Comment by PARKER-X** [comment]
@vcnwafor Finally error resolved i need to install pydantic version 1 redis_om didn;t support pydantic v2ans now error is resolved
Thanks!
